apiVersion: v1
kind: ServiceAccount
metadata:
   name: carol
   namespace: prometheus

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod_reader
  namespace: prometheus
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod_reader_RoleBinding
  namespace: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod_reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:carol