apiVersion: v1
kind: ServiceAccount
metadata:
   name: dave

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: no_access

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: no_access_user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: no_access
subjects:
- kind: ServiceAccount
  name: dave
  namespace: default