---
apiVersion: v1
kind: Namespace
metadata:
  name:  monitoring

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
  namespace: monitoring
  labels:
    app: nginx-monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-monitoring
  template:
    metadata:
      labels:
        app: nginx-monitoring
    spec:
      containers:
      - name: nginx
        image: yerlanagzhigitov/otus-homework-monitoring:v1.0
        ports:
          - name: nginx-port
            containerPort: 8888
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.5.0
        args:
        - -nginx.scrape-uri=http://localhost:8888/basic_status
        ports:
          - name: nginx-exporter
            containerPort: 9113