kind: Service
apiVersion: v1
metadata:
  name: nginx-monitoring
  namespace: monitoring
  labels:
    app: nginx-monitoring
spec:
  type: NodePort
  selector:
    app: nginx-monitoring
  ports:
   - name: nginx-port
     protocol: TCP
     port: 8888
     targetPort: 8888
   - name: nginx-exporter
     protocol: TCP
     port: 9113
     targetPort: 9113