apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 25%
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: server
        image: yerlanagzhigitov/otus-homework1:0.0.1